---
- name: Install php-fpm and deps 
  yum: name={{ item }} state=latest enablerepo=remi,remi-php55
  with_items:    
    - php-fpm
    - php-common
    - php-devel
    - php-cli
    - php-pdo
    - php-gd
    - php-xml
    - php-mbstring
    - php-mcrypt
    - php-mysql

- name: Create Folder for Session
  file: path=/var/lib/php/session state=directory owner=nginx group=nobody mode=770

- name: Create Folder for WDSL
  file: path=/var/lib/php/wsdlcache state=directory owner=nginx group=nobody mode=770

- name: Copy error.log file
  copy: src=error.log dest=/var/log/php-fpm/error.log owner=nginx group=nginx mode=770

- name: Copy slow.log file
  copy: src=slow.log dest=/var/log/php-fpm/slow.log owner=nginx group=nginx mode=770

- name: Copy www.conf file
  template: src=www.conf dest=/etc/php-fpm.d/www.conf

- name: Add php-fpm to chkconfig
  command: chkconfig --add php-fpm

- name: Auto start php-fpm
  command: chkconfig --levels 235 php-fpm on
  notify: restart php-fpm